language: python
python:
  - "3.3"
  - "3.4"

install:
  - pip install -r requirements.txt
  - pip install pytest-cov python-coveralls

script:
  - py.test --cov experimentator tests/

after_success:
  - coveralls
